# Generated by Django 4.2.16 on 2024-12-05 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
